flags:
  text:
    integer-simple: false
packages:
- '.'
- location:
    git: https://github.com/ku-fpg/kure
    commit: 7ce26aa78afbe8d241f859d5789fef6af485bc95
  extra-dep: true
- location:
    git: https://github.com/ku-fpg/hermit
    commit: 5557609f18d83b9acd1aafddaa1cfb3eb64f7c55
  extra-dep: true
- location:
    git: https://github.com/conal/circat
    commit: d3f04f566274ea2b70dc1363c59ca4e9f22b3134
  extra-dep: true
- location:
    git: https://github.com/conal/hermit-extras
    commit: e24ec101739a52356e6c5966e9258c13810cea4e
  extra-dep: true
- location:
    git: https://github.com/ku-fpg/netlist
    commit: 9869fe5eca7b0478bb352d2f14b2d46a01e46938
  subdirs:
  - netlist
  - netlist-to-vhdl
  - verilog
  - netlist-to-verilog
  extra-dep: true
extra-deps:
- Boolean-0.2.3
- MemoTrie-0.6.4
- NumInstances-1.4
- QuickCheck-2.8.1
- TypeCompose-0.9.10
- ansi-terminal-0.6.2.3
- applicative-numbers-0.1.3
- constraints-0.6
- data-default-0.5.3
- data-default-class-0.0.1
- data-default-instances-base-0.0.1
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- dlist-0.7.1.2
- exceptions-0.8.0.2
- hashable-1.2.3.3
- marked-pretty-1.1.2.1
- mtl-2.2.1
- newtype-0.2
- old-locale-1.0.0.7
- operational-0.2.3.2
- parsec-3.1.9
- primitive-0.6.1.0
- random-1.1
- stm-2.4.4
- syb-0.6
- temporary-1.2.0.3
- text-1.2.1.3
- tf-random-0.5
- transformers-compat-0.4.0.4
- treeviz-2.0.3
- ty-0.1.6
- type-unary-0.2.21
- vector-space-0.10.2
resolver: ghc-7.10.2
